# Generated by Django 5.1.1 on 2024-09-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VilleModel',
            fields=[
                ('codePostal', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Code postale')),
                ('nomVille', models.CharField(max_length=32, verbose_name='Nom du ville')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
            },
        ),
    ]
