# Generated by Django 5.1 on 2024-10-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ville', '0002_villemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villemodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
