# Generated by Django 5.1 on 2024-10-11 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='employerContacter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employermodel', verbose_name='Employer concerner'),
        ),
    ]
