# Generated by Django 5.1 on 2024-11-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_clientmodel_employercontacter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='adresseClient',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='fonctionClient',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='interestedClient',
        ),
    ]
