# Generated by Django 5.1 on 2024-10-04 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('villa', '0003_remove_villamodel_employeradmin_and_more'),
        ('ville', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villaModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villa.villamodel', verbose_name='Modèle')),
                ('villeVilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ville.villemodel', verbose_name='Emplacement')),
            ],
        ),
    ]
