# Generated by Django 5.1 on 2024-10-06 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resider', '0001_initial'),
        ('villa', '0003_remove_villamodel_employeradmin_and_more'),
        ('ville', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resider',
            name='villaModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villa', to='villa.villamodel', verbose_name='Modèle'),
        ),
        migrations.AlterField(
            model_name='resider',
            name='villeVilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville', to='ville.villemodel', verbose_name='Emplacement'),
        ),
    ]
