# Generated by Django 5.1 on 2024-10-04 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('villa', '0003_remove_villamodel_employeradmin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillaUnique',
            fields=[
                ('lotVilla', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Lot du villa')),
                ('prix', models.FloatField()),
                ('modelVilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villa.villamodel', verbose_name='Modèle du villa')),
            ],
            options={
                'verbose_name': 'Villa unique',
                'verbose_name_plural': 'Villas uniques',
            },
        ),
    ]
