# Generated by Django 5.1.1 on 2024-09-30 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
        ('ville', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillaModel',
            fields=[
                ('lotVilla', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='Lotissement')),
                ('nomVilla', models.CharField(max_length=32, verbose_name='Nom du villa')),
                ('prixVilla', models.IntegerField(verbose_name='Prix')),
                ('descriptionVilla', models.TextField(verbose_name='Description')),
                ('employerAdmin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employer.employermodel', verbose_name='Publié par')),
                ('villeVilla', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ville.villemodel', verbose_name='ville')),
            ],
            options={
                'verbose_name': 'Villa',
                'verbose_name_plural': 'Villas',
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('villaConcerner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='villa.villamodel')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
