# Generated by Django 5.1 on 2024-10-02 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
        ('villa', '0001_initial'),
        ('ville', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villamodel',
            name='employerAdmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employermodel', verbose_name='Publié par'),
        ),
        migrations.AlterField(
            model_name='villamodel',
            name='villeVilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ville.villemodel', verbose_name='ville'),
        ),
    ]
