# Generated by Django 5.1 on 2024-10-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0004_alter_villamodel_lotvilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villamodel',
            name='lotVilla',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='Lotissement'),
        ),
    ]
