# Generated by Django 5.1 on 2024-10-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0005_alter_villamodel_lotvilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villamodel',
            name='lotVilla',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Code villa'),
        ),
    ]
