# Generated by Django 5.1.1 on 2024-09-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerModel',
            fields=[
                ('matriculeEmployer', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Matricule')),
                ('nomPrenomsEmployer', models.CharField(max_length=100, verbose_name='Nom')),
                ('emailEmployer', models.EmailField(max_length=50, unique=True, verbose_name='E-mail')),
                ('adresseEmployer', models.CharField(max_length=50, verbose_name='Adresse')),
                ('fonctionEmployer', models.CharField(max_length=32, verbose_name='Fonction')),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
            },
        ),
    ]
