# Generated by Django 5.1.1 on 2024-09-30 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('villa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReservation', models.DateField(verbose_name='Date du réservation')),
                ('accompte', models.BooleanField(verbose_name='Escompte de 30%')),
                ('clientReserver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientmodel', verbose_name='Client concerner')),
                ('villaReserver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villa.villamodel', verbose_name='Villa réserver')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
            },
        ),
    ]
