# Generated by Django 5.1 on 2024-10-17 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
        ('villaUnique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='lotReserver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='villaUnique.villaunique', verbose_name='Lotissement choisi'),
        ),
    ]
